site_name: Proxy HTTP com Squid
site_author: Jurandy Soares

repo_url: https://github.com/jurandysoares/proxy-doc
edit_uri: "edit/main/docs"

theme:
  name: material
  language: pt
  palette:
    primary: green

nav:
  - index.md
  - instalacao.md
  - configuracao.md
  - Listas: listas.md

  - ACL:
    - Origem: acl/src.md
    - Destino: acl/dst.md
    - Domínio: acl/dstdomain.md
    - Tempo: acl/time.md
    - Regex: acl/url-regex.md
    - Porta: acl/port.md
    - Autenciação: acl/proxy-auth.md

  - regras.md
  - exemplos.md
  - servico.md
  - log.md
  - outras-confs.md
  - videos.md
  - referencias.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - pymdownx.emoji

plugins:
  - mermaid2

